services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: "${PUID}"
      PGID: "${PGID}"
    volumes:
      - /path/to/media:/media # <-- same mount point
      - /path/to/sonarr/config:/config
      - /path/to/mkvpriority/config:/mkvpriority
    ports:
      - 8989:8989
    restart: unless-stopped

  mkvpriority:
    image: ghcr.io/kennethsible/mkvpriority
    container_name: mkvpriority
    environment:
      WEBHOOK_RECEIVER: "true"
      MKVPRIORITY_ARGS: >
        --archive /config/archive.db
    volumes:
      - /path/to/media:/media # <-- same mount point
      - /path/to/mkvpriority/config:/config
    restart: unless-stopped
