services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - /path/to/media/anime:/anime
      # copy mkvpriority.sh to /config
      - /path/to/sonarr/config:/config
    ports:
      - 8989:8989
    restart: unless-stopped

  mkvpriority:
    image: ghcr.io/kennethsible/mkvpriority
    container_name: mkvpriority
    environment:
      - WEBHOOK_RECEIVER=true
      - MKVPRIORITY_ARGS=
    volumes:
      - /path/to/media/anime:/anime
      - /path/to/database/archive.db:/app/archive.db
    restart: unless-stopped
