services:
  sonarr:
    image: lscr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - /path/to/media:/media # <-- same mount point
      - /path/to/sonarr/config:/config
      - /path/to/mkvpriority/config:/mkvpriority
    ports:
      - 8989:8989
    restart: unless-stopped

  mkvpriority:
    image: ghcr.io/kennethsible/mkvpriority
    container_name: mkvpriority
    user: ${PUID}:${PGID}
    environment:
      # TZ: "America/New_York"
      # CRON_SCHEDULE: "0 0 * * *"
      WEBHOOK_RECEIVER: "true"
      MKVPRIORITY_ARGS: >
        --archive /config/archive.db
      # SONARR_URL: http://sonarr:8989
      # SONARR_API_KEY: ${SONARR_API_KEY}
      # RADARR_URL: http://radarr:7878
      # RADARR_API_KEY: ${RADARR_API_KEY}
    volumes:
      - /path/to/media:/media # <-- same mount point
      - /path/to/mkvpriority/config:/config
    restart: unless-stopped
