# === Input Directories ===
# List of directories to scan recursively for MKV files.
# You can add multiple paths, including network paths.
input_dirs = []


# === Audio Operation Mode ===
# Determines how the selected audio track will be flagged in the MKV:
# - 'default' = Sets the chosen track as default (recommended for most players)
# - 'forced'  = Stronger flag; some players prioritize forced tracks
# - 'disable_strict' = Disables all other non-selected tracks (optional cleanup)
# - 'disable' = Disables only non-selected tracks without language rankings
# - 'enable'  = Re-enables tracks previously disabled (used to undo 'disable')
#
# Recommended: ["default", "disable"]
# Sets the best-scoring audio track as default and disables some non-selected tracks.
# Keeps English dubs available for dual-audio use. Do NOT use "disable_strict" if
# you want to switch audio tracks in your player (e.g., Japanese ↔ English).
audio_mode = ["default", "disable"]


# === Subtitle Operation Mode ===
# Similar to audio_mode, this controls subtitle flags:
# - 'default' = Sets the preferred subtitle as the default track
# - 'forced'  = Additionally flags it as "forced" so players will display it automatically
#
# Recommended: ["default", "forced"]
# This helps ensure subtitles are shown even if the player isn't configured properly.
subtitle_mode = ["default", "forced"]


# === Audio Language Preferences ===
# Language ranking for audio tracks. Higher values are better.
# Default: prioritize Japanese audio, with English dubs as a fallback.
[audio_languages]
jpn = 100
eng = 70
und = 30


# === Audio Codec Priorities ===
# Score audio codecs by quality. Higher values are better.
# This helps pick higher fidelity audio when multiple options exist.

[audio_codecs]
A_DTSHD_MA = 10
A_TRUEHD = 9
A_FLAC = 8
A_DTS = 7
A_EAC3 = 6
A_AC3 = 5
A_AAC = 4
"A_MPEG/L3" = 2


# === Audio Channel Priorities ===
# Prefer audio with more channels (e.g. 5.1 surround over stereo).
[audio_channels]
8 = 9
7 = 8
6 = 10 # Prefer 5.1 Surround
5 = 7
4 = 6
3 = 5
2 = 4
1 = 3


# === Subtitle Language Preferences ===
# Rank subtitle languages by preference.
# 'und' = undefined language, treated as a fallback.
[subtitle_languages]
jpn = 100
eng = 70
und = 30


# === Track Filters (Subtitle Naming Heuristics) ===
# Looks at the track *name* to detect its purpose and assign priority.
# This is especially useful when language or codec alone isn't enough.
# - Full/Dialogue (for English Subs)
# - Signs & Songs (for English Dubs)
# - Commentary/SDH (which should be ranked last)
[track_filters]
dialog = 10
full = 9
honorific = 8
sign = -10
song = -10
commentar = -100
sdh = -100


# === Subtitle Codec Preferences ===
# Ranks subtitle formats by display quality and stylability.
# ASS (SubStationAlpha) is preferred for anime due to typesetting/styling.
[subtitle_codecs]
SubStationAlpha = 2 # stylized subtitles (ASS/SSA)
"SubRip/SRT" = 1    # plain text subtitles (SRT)
"HDMV PGS" = 0      # image-based (used in Blu-rays)
VobSub = 0          # legacy image-based (used in DVDs)
