# === Audio Operation Mode ===
# Determines how the best-scoring audio track will be flagged:
# - 'default' = Sets the chosen track as default (recommended for most players)
# - 'forced'  = Stronger flag; some players prioritize forced tracks
# - 'disabled' = Disables non-selected tracks (ignored by most players)
# - 'enabled'  = Re-enables tracks previously disabled (used to undo 'disabled')
audio_mode = ["default"]


# === Subtitle Operation Mode ===
# Similar to audio_mode, this controls track flags for subtitles:
# - 'default' = Sets the chosen track as default (recommended for most players)
# - 'forced'  = Stronger flag; some players prioritize forced tracks
# - 'disabled' = Disables non-selected tracks (ignored by most players)
# - 'enabled'  = Re-enables tracks previously disabled (used to undo 'disabled')
# This helps ensure subtitles are shown even if the player isn't configured properly.
subtitle_mode = ["default", "forced"]


# === Audio Language Preferences ===
# Default: prioritize Japanese audio over English dubs.
# 'und' = undefined language, treated as a fallback.
[audio_languages]
jpn = 100
eng = 70
und = 30


# === Audio Codec Preferences ===
# Default: prioritize audio tracks with higher fidelity.
[audio_codecs]
A_DTSHD_MA = 10 # DTS-HD Master Audio
A_TRUEHD = 9    # Dolby TrueHD
A_FLAC = 8      # Free Lossless Audio Codec
A_DTS = 7       # DTS
A_OPUS = 6      # Opus
A_EAC3 = 5      # Dolby Digital Plus (Enhanced AC-3)
A_AC3 = 4       # Dolby Digital (AC-3)
A_AAC = 3       # Advanced Audio Coding
"A_MPEG/L3" = 2 # MP3 (MPEG Layer III)


# === Audio Channel Preferences ===
# Default: prioritize audio tracks with more channels.
[audio_channels]
8 = 9  # 7.1 Surround
7 = 8  # 6.1 Surround
6 = 10 # 5.1 Surround (Preferred)
5 = 7  # 5.0 Surround
4 = 6  # Quadraphonic / 4.0 Surround
3 = 5  # 2.1 or 3.0
2 = 4  # Stereo
1 = 3  # Mono


# === Subtitle Language Preferences ===
# Default: prioritize English subtitles for Japanese.
# 'und' = undefined language, treated as a fallback.
[subtitle_languages]
eng = 100
jpn = 90
und = 30


# === Track Filters (Subtitle Naming Heuristics) ===
# Looks at the track *name* to detect its purpose and assign priority.
# This is especially useful when language or codec alone isn't enough.
# - Full/Dialogue (for English subs)
# - Signs & Songs (for English dubs)
# - Commentary/SDH (which should be ranked last)
[track_filters]
full = 10        # dialog subtitles with signs
dialog = 9       # spoken content subtitles
honorific = 8    # dialog subtitles with honorifics
sign = -15       # on-screen text subtitles
song = -15       # lyrics or karaoke subtitles
commentar = -100 # commentary track subtitles
sdh = -100       # hard of hearing subtitles


# === Subtitle Codec Preferences ===
# Ranks subtitle formats by display quality and stylability.
# ASS is preferred for anime due to typesetting/styling.
[subtitle_codecs]
"S_TEXT/ASS" = 2    # stylized subtitles (Advanced SubStationAlpha)
S_SSA = 2           # legacy stylized subtitles (SubStationAlpha)
"S_TEXT/UTF8" = 1   # plain text subtitles (SubRip/SRT)
"S_TEXT/WEBVTT" = 1 # web-based video text (used in streaming)
"S_HDMV/PGS" = 0    # image-based (used in Blu-rays)
S_VOBSUB = 0        # legacy image-based (used in DVDs)
