# === Audio Operation Mode ===
# Determines how the best-scoring audio track will be flagged:
# - 'default' = Sets the chosen track as default (recommended for most players)
# - 'forced'  = Stronger flag; some players prioritize forced tracks
# - 'disabled' = Disables non-selected tracks (ignored by most players)
# - 'enabled'  = Re-enables tracks previously disabled (used to undo 'disabled')
audio_mode = ["default"]

# === Subtitle Operation Mode ===
# Similar to audio_mode, controls track flags for subtitles:
# - 'default' = Sets the chosen track as default (recommended for most players)
# - 'forced'  = Stronger flag; some players prioritize forced tracks
# - 'disabled' = Disables non-selected tracks (ignored by most players)
# - 'enabled'  = Re-enables tracks previously disabled (used to undo 'disabled')
# Ensures subtitles are shown even if the player isn't configured properly.
subtitle_mode = ["default", "forced"]

# === Audio Language Preferences ===
# Example: Prioritize Japanese subs over English dubs.
[audio_languages]
# org = ? # Original Language (Radarr/Sonarr)
jpn = 100 # Japanese
eng = 70  # English
und = 30  # Undefined (Fallback)

# === Audio Codec Preferences ===
# Example: Prioritize audio tracks with higher fidelity.
[audio_codecs]
A_DTSHD_MA = 10 # DTS-HD Master Audio
A_TRUEHD = 9    # Dolby TrueHD
A_FLAC = 8      # Free Lossless Audio Codec
A_DTS = 7       # DTS
A_OPUS = 6      # Opus
A_EAC3 = 5      # Dolby Digital Plus (Enhanced AC-3)
A_AC3 = 4       # Dolby Digital (AC-3)
A_AAC = 3       # Advanced Audio Coding
"A_MPEG/L3" = 2 # MP3 (MPEG Layer III)

# === Audio Channel Preferences ===
# Example: Prioritize audio tracks with more channels.
[audio_channels]
8 = 9  # 7.1 Surround
7 = 8  # 6.1 Surround
6 = 10 # 5.1 Surround (Preferred)
5 = 7  # 5.0 Surround
4 = 6  # Quadraphonic / 4.0 Surround
3 = 5  # 2.1 or 3.0
2 = 4  # Stereo
1 = 3  # Mono

# === Audio Track Filters ===
# Looks at the track name to detect its purpose and assign priority.
# This is especially useful when language or codec alone isn't enough.
[audio_filters]
commentar = -200   # Commentary Track
descriptive = -200 # Visually Impaired

# === Subtitle Language Preferences ===
# Example: Prioritize English subtitles with Japanese audio.
[subtitle_languages]
enm = 110 # English Modified (Anime-Specific)
eng = 100 # English
jpn = 90  # Japanese (Sometimes Mislabled)
und = 30  # Undefined (Fallback)

# === Subtitle Codec Preferences ===
# Example: Prioritize subtitle tracks with higher stylability.
[subtitle_codecs]
"S_TEXT/ASS" = 2    # Stylized Subtitles (Advanced SubStationAlpha)
S_SSA = 2           # Legacy Stylized Subtitles (SubStationAlpha)
"S_TEXT/UTF8" = 1   # Plain Text Subtitles (SubRip/SRT)
"S_TEXT/WEBVTT" = 1 # Web-Based Video Text (Used in Streaming)
"S_HDMV/PGS" = 0    # Image-Based (Used in Blu-rays)
S_VOBSUB = 0        # Legacy Image-Based (Used in DVDs)

# === Subtitle Track Filters ===
# Looks at the track name to detect its purpose and assign priority.
# This is especially useful when language or codec alone isn't enough.
[subtitle_filters]
full = 10        # Spoken Subtitles & On-Screen Text
honorific = 9    # Honorifics Subtitles (Cultural)
official = 8     # Official Subtitles (Localized)
dialog = 7       # Spoken Content Subtitles
sign = -15       # On-Screen Text Subtitles
song = -15       # Lyrics or Karaoke Subtitles
commentar = -200 # Commentary Track Subtitles
sdh = -200       # Deaf & Hard of Hearing
