name: Publish Image to GHCR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: GHCR Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kennethsible
          password: ${{ secrets.GH_PAT }}
      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/kennethsible/mkvpriority:latest
            ghcr.io/kennethsible/mkvpriority:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
      # - name: Build and Push Image
      #   run: |
      #     docker login --username kennethsible --password ${{ secrets.GH_PAT }} ghcr.io
      #     docker build . --tag ghcr.io/kennethsible/mkvpriority:latest
      #     docker push ghcr.io/kennethsible/mkvpriority:latest
