name: Publish Image to GHCR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: kennethsible
          password: ${{ secrets.GH_PAT }}
      - name: Initialize QEMU
        uses: docker/setup-qemu-action@v3
      - name: Initialize Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/kennethsible/mkvpriority:latest
            ghcr.io/kennethsible/mkvpriority:${{ github.ref_name }}
