name: Python CI

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Install Package Manager
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: true
      - name: Initialize Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg mkvtoolnix
      - name: Install Python Dependencies
        run: uv sync --group docker
      - name: Run Unit Tests
        run: uv run pytest -s
