name: Python CI

on: [push]

jobs:
  pytest:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.14']
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install Package Manager
        uses: astral-sh/setup-uv@ae62891fec2bb8e7d6c99fc78c9fec3a63790f8d # v10.0.0
        with:
          enable-cache: true
      - name: Initialize Python ${{ matrix.python-version }}
        run: uv python install ${{ matrix.python-version }}
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg mkvtoolnix
      - name: Install Python Dependencies
        run: uv sync --group docker
      - name: Run Unit Tests
        run: uv run pytest -s
